services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data'
    networks:
      - 'my-network'

  minio:
    image: 'minio/minio:latest'
    container_name: 'minio'
    command: 'server /data --console-address ":9001"'
    environment:
      - 'MINIO_ROOT_USER=minioadmin'
      - 'MINIO_ROOT_PASSWORD=minioadmin'
    ports:
      - '9000:9000'
      - "9001:9001"
    volumes:
      - 'minio_data:/data'
    networks:
      - 'my-network'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio_data:

networks:
  my-network:
    driver: bridge
